default: Driver.class Box.class Boxes.class
	java Driver
	
Driver.class: Driver.java
	javac Driver.java
	
Box.class: Box.java
	javac Box.java

Boxes.class: Boxes.java
	javac Boxes.java

clean:
	rm *.class
